### ISSUE TITLE
[BUG] Duplicate setting in Global Settings

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#381]
Global Settings has a duplicate setting for the Amount of playlists (Default: 30) setting.

Pleases remove or rename as appropriate. :)

**Comment by ukdtom** [comment]
Actually, this is a translation error on my part :(

First occurrence should not have been `Amount of playlists (Default: 30)`  but `Amount of playlist (Default: 30)`

Note the missing s at the end of the word playlist

First option, is used when exporting a playlist, and the one with an s in the end, is used when you export a list of playlists

Will be fixed with the next release
