### ISSUE TITLE
[BUG] When exporting using ExportTools, the ' is missing from the Column "Part File Combined"

### ISSUE THREAD

**Issue by moverperfect** [WebTools-NG/WebTools-NG#386]
**Describe the bug**
When exporting using ExportTools, the ' is missing from the Column "Part File Combined"

**To Reproduce**
1. Have media with ' in the path
2. Export media to csv

**Expected behavior**
Part File Combined should show accurate file location information

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
This line seems to be the culprit https://github.com/WebTools-NG/WebTools-NG/blob/506ac59cfdb9ddfb649a6134bffae9d1c76a9d70/src/components/modules/ExportTools/scripts/et.js#L1304
What is the reason for replacing the ' in this context. Would a new field type need to be added that didn't do the replace for ' or can we remove it from here

**Logs**
Please provide WebTools-NG logs in a zip

**Comment by ukdtom** [comment]
Ahhh.....That one....

This was, as in #386 done due to people having huge issues where characters `'` and `"` was causing like Excel to mess up the output, when use as a qualifier as well, so I simply strip them.

Without that, we had huge probs with users complaining about bad output, so really don't wanna revert that

I might be able to work around this with a setting though, that say keep them as is though
