### ISSUE TITLE
[RFE] Export Tools doesn't allow to pick server

### ISSUE THREAD

**Issue by jschwar313** [WebTools-NG/WebTools-NG#400]
**Is your feature request related to a problem? Please describe.**

When I first tried the export tools part of the application, I didn't know to choose the server from the top of the page.  It's weird that you can't choose the server in the export tools part of the application without choosing it in that area at the top of the page.  It's a bad design.

**Describe the solution you'd like**

Allow a server to be picked in the export tools area.

**Describe alternatives you've considered**

**Additional context**

**Comment by ukdtom** [comment]
Server Selection is on the top of the screen, since it's shared by more than one module, and is as such by design, and documented in the manual here:
https://github.com/WebTools-NG/WebTools-NG/wiki/Export

**Comment by jschwar313** [comment]
Like I said, it’s an incredibly bad design.  Just because it’s documented, doesn’t mean it’s a good design.  Having a server drop down box in the export page that’s redundant and isn’t filled in because it’s dependent on another server drop down box doesn’t make sense.  I would eliminate the server drop down box in the export settings and replace it with a text area that mentions that the server drop down box at the top of the page must have a server selected for the export to work.  Only display that message, in red, if the server isn’t selected.  That would be more intuitive.  After all, screens are supposed to be intuitive, right?  We shouldn’t depend on documentation and having a user spend time trying to figure out a bad design.

**Comment by ukdtom** [comment]
_Having a server drop down box in the export page that’s redundant and isn’t filled in because it’s dependent on another server drop down box doesn’t make sense._

But there's only one server selection box, and that's on the top screen!
There's no server selection box in neither ET screen nor in ET-Settings screen

When said, there's a GHI to auto-select, if the user only have one server
Ref: https://github.com/WebTools-NG/WebTools-NG/issues/148
