### ISSUE TITLE
[BUG] ET Modules Year on shows not working

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#486]
Shows as N/A

When using All Level, we call each show with /children and then the key is: parentYear

**Comment by ukdtom** [comment]
Fix will be in the next release

**Comment by trumpy81** [comment]
The TVDB ID is not working on shows either :(

It simply outputs N/A instead of the ID.

Again, when trying to create a custom level, I cannot input the name of the custom level until after I go to the Help menu and select About WebTools.

Also, after creating a Custom Level and using it, then go back to Custom Levels, the name of the custom level is listed as N/A instead of the name it was given (Test in this case).

**Comment by ukdtom** [comment]
Hi @trumpy81 

Please use separate GHI's for different issues, since otherwise I simply can't track them!

And TVDB ID was caused by the same issue as this one

**Comment by trumpy81** [comment]
OK will do and thanks. :)

**Comment by ukdtom** [comment]
Added the translation error as a GHI ;)

**Comment by trumpy81** [comment]
Kewl and thanks :)

I'm not sure what is going on with the Custom levels, it seems to have fixed itself now ... very strange ... lol
