### ISSUE TITLE
[RFE] Refactor Settings

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#509]
Settings are now getting too complicated, so we need to do a complete refactor of this =>

- [x] Global settings
  -  [x] PMS settings
  -  [x] Export Settings
  -  [x] Lib Mapping
 - [x] ExportTools
 - [x] Find Media

- [x] @trumpy81 does the Wiki

This sadly also involves a lot of Wiki page changes, sorry for that @trumpy81 , but WT-NG is indeed evolving beyond what I originally thought about ;)

More to come, when the time is

**Comment by trumpy81** [comment]
No problem, bring it on !! ... lol

**Comment by ukdtom** [comment]
And Wiki is needed ;)

Preview found here:

https://www.dropbox.com/sh/7o2ywjl02z2dby2/AAAcyezuMrCIAsiZvEKiu_3Wa?dl=0

**Comment by ukdtom** [comment]
From the changelog:
* [#498 Add preferences to shows export](https://github.com/WebTools-NG/WebTools-NG/issues/498)
* [#500 Library Path Mapping](https://github.com/WebTools-NG/WebTools-NG/issues/500)
* [#505 FindMedia](https://github.com/WebTools-NG/WebTools-NG/issues/505)
* [#509 Refactor Settings](https://github.com/WebTools-NG/WebTools-NG/issues/509)
* [#512 ET Intro Start/End isn't exported](https://github.com/WebTools-NG/WebTools-NG/issues/512)
* [#514 Bring back EN translations from Romain](https://github.com/WebTools-NG/WebTools-NG/issues/514)

**Comment by trumpy81** [comment]
Wiki has been updated!

I did notice a few anomalies though.

1. The Global Settings page shows text links instead of buttons. Can these be changed to the familiar green buttons?
2. The Export link on the Global Settings page, can this be changed to ExportTools Settings?
3. On the Export page, can the title be changed to ExportTools Settings?
4. On the Library Mapping page, Library is misspelled in `Select Media Libary`, it should be `Select Media Library`
5. The ET Width*Height settings for Art and Poster images are missing? Are they no longer used/available?

**Comment by ukdtom** [comment]
1. Unsure here, since we need the text regardless, but will look into maybe adding both
2. I've seen that as well ;) Will look into it
3. No, since Export is a global one, also used by Find Media and Plex.tv module (All modules that produce a file)
4. Same as above
5. It's in the English translation on POEdit, and I've updated it
6. Specific settings only for ExportTools, are accessed on the ET module top right gear

![image](https://user-images.githubusercontent.com/4699449/177002442-c77c982e-c5c3-4d6c-986f-c6a1487cd96e.png)

![image](https://user-images.githubusercontent.com/4699449/177002454-ca7dcb58-2fab-447c-95a3-e32090ab67e2.png)


7. Those settings are for Find Media only

**Comment by ukdtom** [comment]
So guess we need a wiki page for specific ET settings, like we have for Find Media

**Comment by trumpy81** [comment]
The Wiki has been updated with the ExportTools settings.

The Global Settings > Export page does NOT contain settings for Find Media. This page ONLY contains settings relevant to ExportTools.

I suggested moving the Find Media (and ExportTools) settings into Global Settings in order to consolidate all settings in a single area.

This would make a persons work flow much more unified. Instead of having to jump to several different locations in order to make settings changes, all changes may be made in a single location, Global Settings > X module.

This is especially important since the folder location for Find Media MUST be changed each time you change the library for Find Media. At present, that must be done in two separate locations (The module itself and in Library Mapping). Forgetting to change one of the settings will no doubt result in operation failure and frustration for the user.

**Comment by trumpy81** [comment]
Also, under Plex Media Server, can we change Settings > Server Settings, so that it is a little more clear what that module is?

**Comment by ukdtom** [comment]
FM use the CSV settings, like delimiter, N/A and Export Dir.
And if I add everything under global settings, I once more ends up with a settings page that's too crowded, IMHO

The idea is:
* A setting shared among multiple modules, goes into the global one
*  A setting that is only used by a single module, resides under that modules settings

> This is especially important since the folder location for Find Media MUST be changed each time you change the library for Find Media

What do you mean?

**Comment by trumpy81** [comment]
I get where you are coming from, but try to look at it from a users perspective. You must bounce around to different areas to make settings changes, all of which effect the module you are using. The settings locations can be difficult to remember, especially when you only use a program occasionally.

In my view, it is far easier to remember where the settings are if they are in one location and not several.

> What do you mean?

I mean that you select a library on the Find media module page, but first you must go to the Library Mapping page and make sure the local and PMS directories are set to the correct locations.

If you do NOT do that, then Find Media may fail due to an incorrect address being used and the user may be unaware of that situation.

This is especially true if the folder/s exist on your NAS for example.

I have at least one library where the local location must be manually set each time, because it resides on one of my NAS, but NOT in the Movies folder. Too easy to forget to change the location in Library Mapping and then Find Media fails to report anything missing.

**Comment by ukdtom** [comment]
I'm sadly not skilled enough to handle deep links into a tabbed component, which is needed for this

![image](https://user-images.githubusercontent.com/4699449/177010094-c54eb76f-8e4b-4e75-aa8f-5fe28cc34bc6.png)

When said, I miss such a deep link in the Find Media Settings as well

**Comment by trumpy81** [comment]
The buttons I showed would simply link to pages containing settings etc., they can be fake pages in the interface perhaps?

It does not matter where they actually are, as long as they appear in the right hand pane at the appropriate time/place. Other buttons would link back to the appropriate settings pages though.

I say that, not really knowing what the actual coding environment looks like, so forgive me if I am off base here.

That link you show above does help :)

I will make a note of it on the wiki too.

**Comment by ukdtom** [comment]
Question:

> I mean that you select a library on the Find media module page, but first you must go to the Library Mapping page and make sure the local and PMS directories are set to the correct locations.

If you do NOT do that, then Find Media may fail due to an incorrect address being used and the user may be unaware of that situation.

But does the path change all the time?

And note that I just updated the preview, so please redownload again

Changed:
* Global Export settings now return to where  it came from, when pressing return button
* Tooltips in Global Settings now shows to the right of the text => not blocking the link
* Added direct link in Find Media settings to Global Export, just like we have in ExportTools settings page

**Comment by trumpy81** [comment]
> But does the path change all the time?

Yes, it is blank, no path defined, whenever I open WebTools-NG.

![Screenshot 2022-07-03 124508](https://user-images.githubusercontent.com/12381786/177022479-ad568948-bec9-48d1-a6d6-6783856f36d1.png)

Mapped Network Drives:
Y:\Movies\Movie Extras\Bonus Material
Z:\Movies\Movie Extras\Bonus Material 
UNC addresses:
\\\DiskStation\Media\Movies\Movie Extras\Bonus Material
\\\PlexStation\Media\Movies\Movie Extras\Bonus Material
Actual address on both NAS:
/volume1/Media/Movies/Movie Extras/Bonus Material
/volume1/Media/Movies/Movie Extras/Bonus Material

It is easy enough to correct the address, but I need to do that each time I select that library or any other library on the NAS, except for the Movies library. All of the other Libraries show "Click to define" in Library Mapping, but the Movies library is always properly defined? 

![image](https://user-images.githubusercontent.com/12381786/177022542-b0b3fb0e-c913-45c5-9533-3b4eaf597a91.png)

I will write up some GHI's with the proposed changes and any issues I find. You can address them when you return from vacation (you lucky sod) :p

I hope you have a good vacation :)

**Comment by trumpy81** [comment]
I need to make a correction. It appears that the defined path for a library is being retained after closing and reopening WebTools-NG.

I am going to blame it on Windows 11 ... it sux! ... lol

**Comment by ukdtom** [comment]
Wiki's seems fine, so closing this
