### ISSUE TITLE
[BUG] ET Suggested file naming - incorrect output

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#530]
**Describe the bug**
When using suggested file naming and having selected TMDB as the DB of choice, the suggested file/folder name contains incorrect data. 

**E.G.**  Aladdin (2019) {tmdb-tt6139732}

This file name contains the tmdb identifier coupled with an imdb item number (as denoted by tt).
The correct identifier in this case should be imdb and NOT tmdb

This does not apply to all of the file/folder names in the .csv output file, only some files use the incorrect db identifier.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select TMDB in the `Default Id for suggested folder and filename for movies` in ET Settings
2. Select `Suggest Naming` in the Export Level drop down menu
3. View the output file
4. See the errors

**Expected behaviour**
imdb references should be identified with imdb and NOT tmdb.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

**Additional context**
[ROGStrix_Movies 4K_Movie_Movies_Suggest Naming_Item 0-36_2022.07.13_12.42.47.csv](https://github.com/WebTools-NG/WebTools-NG/files/9098562/ROGStrix_Movies.4K_Movie_Movies_Suggest.Naming_Item.0-36_2022.07.13_12.42.47.csv)

**Comment by ukdtom** [comment]
@trumpy81 

Having a hard time reproducing here :(

Below two samples, one with IMDB and the other with TMDB

[WinTst2_TEST Movies_Movie_Movies_Suggest Naming_Item 0-2_2022.07.16_5.09.44.csv](https://github.com/WebTools-NG/WebTools-NG/files/9126096/WinTst2_TEST.Movies_Movie_Movies_Suggest.Naming_Item.0-2_2022.07.16_5.09.44.csv)
[WinTst2_TEST Movies_Movie_Movies_Suggest Naming_Item 0-2_2022.07.16_5.08.37.csv](https://github.com/WebTools-NG/WebTools-NG/files/9126097/WinTst2_TEST.Movies_Movie_Movies_Suggest.Naming_Item.0-2_2022.07.16_5.08.37.csv)

Could you perhaps try again?

**Comment by trumpy81** [comment]
I ran the test again, this time using one of my NAS as the server instead of my PC.
The results were the same though, a mix of tmdb and imdb naming.

[DiskStation_Movies 4K_Movie_Movies_Suggest Naming_Item 0-36_2022.07.17_2.23.23.csv](https://github.com/WebTools-NG/WebTools-NG/files/9126179/DiskStation_Movies.4K_Movie_Movies_Suggest.Naming_Item.0-36_2022.07.17_2.23.23.csv)

**Comment by trumpy81** [comment]
I ran the test again on my Movies library (6338 Movies) and the results are much the same.

[DiskStation_Movies_Movie_Movies__Item 0-6338_2022.07.17_2.27.28.csv](https://github.com/WebTools-NG/WebTools-NG/files/9126192/DiskStation_Movies_Movie_Movies__Item.0-6338_2022.07.17_2.27.28.csv)

**Comment by ukdtom** [comment]
Hopefully found the issue, and blame both me and you ;)

**You**:

You have migrated your libraries to the new native agents, which is good, but you have not done a `refresh metadata` on the libraries afterwards.
As such, only medias you have added after the migration, will contain the ID's for imdb, tmdb and tvdb

Warcraft:
![image](https://user-images.githubusercontent.com/4699449/179370372-d6ef5eff-0e0b-44af-8e9d-39880f3bfb4f.png)


Medias before that only have the old imdb legacy guid

Aladdin:
![image](https://user-images.githubusercontent.com/4699449/179370400-b4554874-53a5-425e-9d8d-14ef7e64a543.png)


**Me**:
When I couldn't find a valid tmdb-id, I should migrate back to imdb, which I did, but the rutine messed up, since no new native imdb-id was present, and failed in the procedure to use the old legacy one :(

Hopefully, this is all fixed now, and if not, please reopen
You can test by downloading a new build from DB

When tested, and if OK, I strongly suggest to `refresh metadata` since other new fancy things from Plex will fail as well (Discovery) due to a missing Plex Guid
Warcraft
![image](https://user-images.githubusercontent.com/4699449/179370435-0c2cc80b-cff6-45e9-8bce-7351626641e0.png)


And note, that if naming is not perfect, you might end up with medias getting dropped or mismatched ;)

**Comment by trumpy81** [comment]
That is not so. All of my affected libraries have had Refresh Metadata run on them several times since the libraries were updated to the new Plex agent (years ago), so I do not believe that is the cause. They should also be updated during maintenance every once in a while.

Aladdin (2019) {tmdb-tt6139732}

Aladdin shows the incorrect naming in the .csv file, but has the following GUID's.

<Guid id="imdb://tt9848626"/>
<Guid id="tmdb://585083"/>
<Guid id="tvdb://79179"/>

It's worth noting, that the imdb item numbers do not match either. The Get Info XML file shows a different imdb item number to the .csv file. The .csv file number is correct, but the XML file is incorrect (matches to Hotel Transylvania - Transformia)?

[Aladdin (2019) 4K.txt](https://github.com/WebTools-NG/WebTools-NG/files/9126824/Aladdin.2019.4K.txt)

I will test the new build and report back with my findings.

**Comment by trumpy81** [comment]
Build 1.0.0 installed and the problem seems to have been fixed. :)

The imdb item numbers are now identified correctly with imdb-ttxxxxxxx.
