### ISSUE TITLE
[RFE] Save/Restore all Server Settings

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#562]
Is it plausible, feasible, to let Server Settings save all current settings and then be able to restore them to a server?

This feature could allow one to synchronise the settings across multiple servers (saving to each server, one at a time) or simply restore the settings to an old or new server.

Just a thought, what do you think?

**Comment by ukdtom** [comment]
Since Server Settings are stored either in a Preferences.xml file, a plist file or in the registry depending on the OS, this would be a complicated thing to do, since server might be remote
As such, we would have to walk each setting, and then set it using the Rest API, and each setting has, if even existing, a different endpoint.

As such, I would deem this out of scope, since users could export registry into a file, and run that, or simply copy prefs.xml or plist files
