### ISSUE TITLE
[RFE] Unsupported AppStore

### ISSUE THREAD

**Issue by electblake** [WebTools-NG/WebTools-NG#678]
**Feature**
I want a new an improved Unsupported AppStore for managing plex plugins

**Alternatives**
I have considered forking WebTools UAS as Stand-Alone UAS Plugin, or even building another stand-alone UAS app, but I'd rather keep within community, and WebTools-NG is where community is.

**Approach**

This can be inspired by WebTools.bundle https://github.com/ukdtom/WebTools.bundle/wiki/UAS

Finally, I'd love to model after Jellyfin plugins, with [manifests](https://jellyfin.org/docs/general/server/plugins/#repositories) and the like - it's a nice interface and very user friendly imho

**Initial Requirements**
- Accepts manifests or git urls
- Installs bundle from git repo into plex plugins directory
- Lists plugins available, and installed
- Check if plugin has upstream updates (via git)
- Update (aka git-pull) plugins

**Comment by ukdtom** [comment]
Sorry, but UAS depends on WebTools.bundle

Development on that has stopped

**Comment by electblake** [comment]
I am aware that dev stopped, I was suggesting adding it to this project - as this one is alive

**Comment by electblake** [comment]
request is for plug-in management feature.

**Comment by trumpy81** [comment]
Plugins are no longer being developed because Plex announced, quite some time ago, that plugins would eventually be removed completely.

Plex does NOT provide any mechanism within their current API to handle plugins, therefore, most operations expected of a 'plugin' are simply NOT available.

In other words, WebTools-NG does NOT have the ability to modify the behaviour of Plex and is restricted to the available API calls only.

That said, the API does provide a good deal of functionality and Tommy is working his 'heiny' off to take full advantage of that with WebTools-NG.

**Comment by electblake** [comment]
I see,

Plex announced plugins were being removed some time ago, and yet plugins still work today. I actively manage a few.

That's fine, I'll look elsewhere for my needs, a git-based plugin manager is all I really need (and what Webtools.bundle provided)

**Comment by ukdtom** [comment]
UAS in WebTools.bundle still works!

**Comment by electblake** [comment]
> UAS in WebTools.bundle still works!

ok then :) I really should just keep using UAS and maybe fork/adopt if I want more features 👍🏼 

Appreciate the discussion none-the-less!

(and I'll look for another avenue to contribute to webtools-ng ;))
